apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginflix-backend
  namespace: ginflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ginflix-backend
  template:
    metadata:
      labels:
        app: ginflix-backend
    spec:
      containers:
        - name: backend
          image: ginflix-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: ginflix-backend-config
                  key: MONGO_URI
            - name: AUTH_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: ginflix-backend-config
                  key: AUTH_DISABLED
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-backend
  namespace: ginflix
spec:
  type: NodePort   
  selector:
    app: ginflix-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080        
      targetPort: 8080  
      nodePort: 30081  
