apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginflix-frontend
  namespace: ginflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ginflix-frontend
  template:
    metadata:
      labels:
        app: ginflix-frontend
    spec:
      containers:
        - name: frontend
          image: ginflix-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-frontend-config
                  key: BACKEND_URL
            - name: STREAM_URL
              valueFrom:
                configMapKeyRef:
                  name: ginflix-frontend-config
                  key: STREAM_URL
            - name: AUTH_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: ginflix-frontend-config
                  key: AUTH_DISABLED
---
apiVersion: v1
kind: Service
metadata:
  name: ginflix-frontend
  namespace: ginflix
spec:
  type: NodePort
  selector:
    app: ginflix-frontend
  ports:
    - name: http
      port: 80     
      targetPort: 80
      nodePort: 30080
