kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Frontend (Service NodePort 30080 → containerPort 30080)
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # Backend (Service NodePort 30081 → containerPort 30081)
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
      # Streamer (Service NodePort 30082 → containerPort 30082)
      - containerPort: 30082
        hostPort: 30082
        protocol: TCP
